# Convolution As Matrix-Vector Muliplication

There are two types of common convolution

1. Linear convolution
2. Circular convolution

Both of them can be expressed as matrix-vector muliplication, but only the latter one could be expressed as muliplication in frequency domain directly. (Linear convolution is ok, but we need an extra transformation)

In [1]:
import numpy as np

Suppose `f` is the input signal, `h` is the convolution filter.

In [7]:
f = np.array([[2,5,3],[1,4,1]])
h = np.array([[1,-1]])
print(f)
print(h)

[[2 5 3]
 [1 4 1]]
[[ 1 -1]]


`convolve2d` performs linear convolution, and `conv2` is the corresponding Matlab version. 

Recall that in convolution, we need to **filpped filter first**, then perform a weighted average on the input signal. The linear convolution pads input with zero, while the circular convolution uses reflection padding (we will see later).

In [10]:
from scipy.signal import convolve2d
convolve2d(f,h)

array([[ 2,  3, -2, -3],
       [ 1,  3, -3, -1]])

There is no specific predefined circular convolution function in numpy and Matlab. We could do it mannully 

In [11]:
from numpy.fft import ifft2, fft2

In [18]:
g_fft = ifft2(fft2(f)*fft2(h,(2,3))).real.round(3);
print(g_fft)

[[-1.  3. -2.]
 [-0.  3. -3.]]


In [21]:
H1 = np.array([[1, 0, -1],
               [-1, 1, 0],
               [0, -1, 1]]);
H2 = np.array([[0, 0, 0],
               [0, 0, 0],
               [0, 0, 0]]);
# H = [H1 H2;
#      H2 H1;];
H = np.column_stack([np.row_stack([H1,H2]), np.row_stack([H2, H1])])
print(H)

[[ 1  0 -1  0  0  0]
 [-1  1  0  0  0  0]
 [ 0 -1  1  0  0  0]
 [ 0  0  0  1  0 -1]
 [ 0  0  0 -1  1  0]
 [ 0  0  0  0 -1  1]]
